name: Run the specs
on: [push, workflow_dispatch]
env:
  CXX: g++-4.9

jobs:
  ci:
    name: Test and coverage
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12, 13, 14]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install platform dependencies
        run: sudo apt-get install -y libcairo2-dev libjpeg8-dev libpango1.0-dev libgif-dev

      - name: Install project dependencies
        run: |
          npm explore npm -g -- npm install node-gyp@latest
          npm install
          npm install canvas # optional, needed for server tests

      - name: Run tests
        run: npm run coveralls
